config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :likes

  root "events#index"

  resources :events do
    resources :registrations
    resources :likes
  end

  resource :session, only: [:new, :create, :destroy]

  resources :users
  get "singup" => "users#new"

end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event

  has_secure_password

  validates :name, presence: true

  validates :email, format: { with: /\S+@\S+/ },
                    uniqueness: { case_sensitive: false }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @registrations = @user.registrations
    @liked_events = @user.liked_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to events_url, status: :see_other,
      alert: "Account successfully deleted!"
  end

private

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to events_url, status: :see_other unless current_user?(@user)
  end

  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
  <% if current_user?(@user) %>
    <div class="actions">
      <%= link_to "Edit Account", edit_user_path(@user),
                      class: "button edit" %>
      <%= link_to "Delete Account", @user,
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: "button delete" %>
    </div>
  <% end %>
  <% if @registrations.present? %>
    <h3>Registrations</h3>
    <% @registrations.each do |r| %>
      <div class="registration">
        <div class="image">
          <%= link_to image_tag(r.event.image_file_name), r.event %>
        </div>
        <div class="name">
          <%= link_to r.event.name, r.event %>
        </div>
        <div class="date">
          <%= time_ago_in_words(r.created_at) %> ago
        </div>
      </div>
    <% end %>
  <% end %>
  <% if @liked_events.present? %>
    <h3>Liked Events</h3>
    <div class="liked-events">
      <% @liked_events.each do |event| %>
        <%= link_to image_tag(event.image_file_name), event %>
      <% end %>
    </div>
  <% end %>
</section>