config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :likes

  root "events#index"

  resources :events do
    resources :registrations
    resources :likes
  end

  resource :session, only: [:new, :create, :destroy]

  resources :users
  get "singup" => "users#new"

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :name, :location, presence: true

  validates :description, length: { minimum: 25 }

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :capacity, numericality:
                       { only_integer: true, greater_than: 0 }

  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a JPG or PNG image"
  }

  scope :past, -> { where("starts_at < ?", Time.now).order("starts_at") }
  scope :upcoming, -> { where("starts_at > ?", Time.now).order("starts_at") }
  scope :free, -> { upcoming.where(price: 0.0).order(:name) }
  scope :recent, ->(max=3) { past.limit(max) }

  def free?
    price.blank? || price.zero?
  end

  def sold_out?
    (capacity - registrations.size).zero?
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    case params[:filter]
    when "past"
      @events = Event.past
    when "free"
      @events = Event.free
    when "recent"
      @events = Event.recent
    else
      @events = Event.upcoming
    end
  end

  def show
    @event = Event.find(params[:id])
    @likers = @event.likers
    @categories = @event.categories
    if current_user
      @like = current_user.likes.find_by(event_id: @event.id)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, status: :see_other
  end

private

  def event_params
    params.require(:event).
      permit(:name, :description, :location, :price, :starts_at,
             :capacity, :image_file_name, category_ids: [])
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def price(event)
    if event.free?
      "Free"
    else
      number_to_currency(event.price, precision: 0)
    end
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d at %I:%M %P")
  end

end

app/views/events/_form.html.erb
<%= form_with(model: event) do |f| %>

  <%= render "shared/errors", object: event %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :starts_at %>
  <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

  <%= f.label :capacity %>
  <%= f.number_field :capacity %>

  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>

  <div class="checkboxes">
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
  </div>

  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <section class="event">
    <div class="image">
      <%= image_tag event.image_file_name %>
    </div>
    <div class="summary">
      <h2><%= link_to event.name, event %></h2>
      <h3><%= day_and_time(event) %> in <%= event.location %></h3>
      <span class="price">
        <%= price(event) %>
      </span>
      <p>
        <%= truncate(event.description, length: 35, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Event", new_event_path, class: "button" %>
  </section>
<% end %>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
  <div class="image">
    <%= image_tag @event.image_file_name %>
    <% if current_user %>
      <div class="likes">
        <%= like_or_unlike_button(@event, @like) %>
        <div class="count">
          <%= @likers.size %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="details">
    <h1><%= @event.name %></h1>
    <h2>
      <%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event) %>
    </h2>
    <h3>
      <%= day_and_time(@event) %> in <%= @event.location %>
    </h3>
    <p>
      <%= @event.description %>
    </p>

    <div class="register">
      <%= register_or_sold_out(@event) %>
      <p>
        <%= link_to "Who's registered?", event_registrations_path(@event) %>
      </p>
    </div>
  </div>
  <aside>
    <% if @likers.present? %>
      <h4>Liked By</h4>
      <ul>
        <% @likers.each do |user| %>
          <li>
            <%= link_to user.name, user %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <% if @categories.present? %>
      <h4>Categories</h4>
      <ul>
        <% @categories.each do |c| %>
          <li><%= c.name %></li>
        <% end %>
      </ul>
    <% end %>
  </aside>
</section>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_event_path(@event), class: "button" %>
    <%= link_to "Delete", @event, class: "button",
          data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>
  </section>
<% end %>